###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/memory_system/impl/hbm_stack_memory_system.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, ChildList


class HBMStack(Component):
    impl = "HBMStack"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    host_phy_latency_ps = Param(int, default=0)
    base_die_hop_ps = Param(int, default=0)
    pim_mesh_width = Param(int, default=4)
    ingress_buffer = Param(int, default=32)
    request_bytes = Param(int, default=64)
    stacks = Param(int, default=1)
    host_stack_link_ps = Param(int, default=0)
    source_mapping = Param(str, default="per_channel")
    addressing = Param(str, default="channel_interleave")
    cores_per_stack = Param(int, default=1)
    inter_unit = Param(str, default="host")
    inter_unit_latency_ps = Param(int, default=40000)
    inter_unit_bw_gbps = Param(float, default=12.8)
    controllers = ChildList("controller")
