###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/memory_system/impl/hmc_memory_system.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, ChildList


class HMC(Component):
    impl = "HMC"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    pim_mode = Param(bool, default=False)
    network_overhead = Param(bool, default=False)
    host_links = Param(int, default=4)
    link_width = Param(int, default=16)
    lane_speed_gbps = Param(float, default=30.0)
    payload_flits = Param(int, default=16)
    max_block_bits = Param(int, default=8)
    link_buffer = Param(int, default=32)
    max_tags = Param(int, default=2048)
    pim_mesh_width = Param(int, default=6)
    pim_burst_count = Param(int, default=2)
    addressing = Param(str, default='RoCoBaVa')
    controllers = ChildList("controller")
