###############################################################################
# AUTO-GENERATED FILE — DO NOT EDIT
#
# Generated by: python -m ramulator codegen
# Source:       src/ramulator/memory_system/impl/hmc_network_memory_system.cpp
#
# Regenerate:   python -m ramulator codegen
###############################################################################
from ramulator.components import Component
from ramulator.param import Param, ChildList


class HMCNetwork(Component):
    impl = "HMCNetwork"
    clock_ratio = Param(int, required=True, cpp_type="unsigned int")
    stacks = Param(int, default=1)
    stack_links = Param(int, default=4)
    link_width = Param(int, default=16)
    lane_speed_gbps = Param(float, default=30.0)
    payload_flits = Param(int, default=4)
    max_block_bits = Param(int, default=7)
    link_buffer = Param(int, default=32)
    max_tags = Param(int, default=2048)
    rmab_size = Param(int, default=32)
    quadrant = Param(bool, default=True)
    ideal_memnet_type = Param(int, default=0)
    topology_file = Param(str, required=True)
    switch_config = Param(str, required=True)
    addressing = Param(str, default='RoChBgBaCuVaCl')
    controllers = ChildList("controller")
